CREATE TABLE IF NOT EXISTS "public"."ping" (
    "id" bigint NOT NULL,
    "message" "text" DEFAULT 'Pong!'::"text" NOT NULL
);


ALTER TABLE "public"."ping" OWNER TO "postgres";


ALTER TABLE "public"."ping" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ping_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."ping"
    ADD CONSTRAINT "ping_pkey" PRIMARY KEY ("id");



CREATE POLICY "Enable read access for all users" ON "public"."ping" FOR SELECT USING (true);

ALTER TABLE "public"."ping" ENABLE ROW LEVEL SECURITY;