create table "public"."ping" (
    "id" bigint generated by default as identity not null,
    "message" text not null default 'Pong!'::text
);


alter table "public"."ping" enable row level security;

CREATE UNIQUE INDEX ping_pkey ON public.ping USING btree (id);

alter table "public"."ping" add constraint "ping_pkey" PRIMARY KEY using index "ping_pkey";

grant delete on table "public"."ping" to "anon";

grant insert on table "public"."ping" to "anon";

grant references on table "public"."ping" to "anon";

grant select on table "public"."ping" to "anon";

grant trigger on table "public"."ping" to "anon";

grant truncate on table "public"."ping" to "anon";

grant update on table "public"."ping" to "anon";

grant delete on table "public"."ping" to "authenticated";

grant insert on table "public"."ping" to "authenticated";

grant references on table "public"."ping" to "authenticated";

grant select on table "public"."ping" to "authenticated";

grant trigger on table "public"."ping" to "authenticated";

grant truncate on table "public"."ping" to "authenticated";

grant update on table "public"."ping" to "authenticated";

grant delete on table "public"."ping" to "service_role";

grant insert on table "public"."ping" to "service_role";

grant references on table "public"."ping" to "service_role";

grant select on table "public"."ping" to "service_role";

grant trigger on table "public"."ping" to "service_role";

grant truncate on table "public"."ping" to "service_role";

grant update on table "public"."ping" to "service_role";

create policy "Enable read access for all users"
on "public"."ping"
as permissive
for select
to public
using (true);



